#!/bin/sh

readonly PROJECT_ROOT="$(dirname "$0")/.."

is_installed() {
  command -v "$1" > /dev/null 2>&1
  return "$?"
}

if is_installed "shellcheck"; then
  echo "Running shellcheck..."

  shellcheck --shell=sh \
    "${PROJECT_ROOT}"/bin/* \
    "${PROJECT_ROOT}"/lib/*

  if [ $? -eq 0 ]; then
    echo "shellcheck passed"
  else
    exit 1
  fi
else
  echo "Skipping shellcheck test: shellcheck utility not found in PATH."
  echo "Please install shellcheck or make sure it's included in PATH."
fi

echo

if is_installed "bats"; then
  echo "Running BATS tests..."
  bats "${PROJECT_ROOT}/test/suites"
else
  echo "Skipping BATS tests: BATS not found in PATH."
  echo "Please install BATS or make sure it's included in PATH."
fi
